# Generated by Django 4.0.3 on 2022-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
                ('playlists_created', models.IntegerField(default=0)),
                ('songs_discovered', models.IntegerField(default=0)),
            ],
        ),
    ]
