# Generated by Django 4.0.3 on 2022-09-05 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyarchiveapp', '0002_rename_songs_discovered_user_unique_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
