# Generated by Django 4.0.3 on 2022-09-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyarchiveapp', '0003_alter_user_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_songs',
        ),
    ]
